apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: alzheimer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Après : kubectl apply -f .../local-path-storage.yaml → classe « local-path »
  storageClassName: local-path
